# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'number-to-word'
  tag: $(Build.BuildId)
  acrName: 'aksregistryname.azurecr.io'

steps:

# Step 1: Build Docker image
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: Dockerfile
    tags: |
      latest

# Step 2: Login to ACR
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: '
projectserviceconnection'

# Step 3: Push image to ACR
- task: Docker@2
  displayName: Push image
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      latest
